version: '3'

services:
  app:
    container_name: nest-budget
    restart: always
    build: .
    links:
      - mysql
    ports:
      - '9000:3000'
  mysql:
    image: mysql:5.7
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: budget
      MYSQL_USER: nest
      MYSQL_PASSWORD: nest