version: '3'

services:
  node:
    build: .
    container_name: nest_budget
    image: node:10-jessie
    ports:
      - '9000:3000'
    command: npm run start:dev
    volumes:
      - .:/app
    links:
      - mysql
  mysql:
    image: mysql:5.7
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: budget
      MYSQL_USER: nest
      MYSQL_PASSWORD: nest